// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_svkztx0yolIQlYvtSmNZ8l-GaubX7Xw',
    appId: '1:376961493506:web:b496dce3a2dbb5f438551b',
    messagingSenderId: '376961493506',
    projectId: 'servicehub-6191b',
    authDomain: 'servicehub-6191b.firebaseapp.com',
    storageBucket: 'servicehub-6191b.appspot.com',
    measurementId: 'G-9K6T856X6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-F7XjYK4nLVfGRjfjtEisnmdSCKKO27w',
    appId: '1:237366612156:android:02dea05459f7f86e3cc0b9',
    messagingSenderId: '237366612156',
    projectId: 'servicehub-98070',
    storageBucket: 'servicehub-98070.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApg4c48KTUXDW1VZ6VCkwe9LVBXMQDelM',
    appId: '1:376961493506:ios:ac103f2e6d9c3f3838551b',
    messagingSenderId: '376961493506',
    projectId: 'servicehub-6191b',
    storageBucket: 'servicehub-6191b.appspot.com',
    iosBundleId: 'com.example.service_hub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApg4c48KTUXDW1VZ6VCkwe9LVBXMQDelM',
    appId: '1:376961493506:ios:ac103f2e6d9c3f3838551b',
    messagingSenderId: '376961493506',
    projectId: 'servicehub-6191b',
    storageBucket: 'servicehub-6191b.appspot.com',
    iosBundleId: 'com.example.service_hub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_svkztx0yolIQlYvtSmNZ8l-GaubX7Xw',
    appId: '1:376961493506:web:c33c45e539bd67f338551b',
    messagingSenderId: '376961493506',
    projectId: 'servicehub-6191b',
    authDomain: 'servicehub-6191b.firebaseapp.com',
    storageBucket: 'servicehub-6191b.appspot.com',
    measurementId: 'G-2CVC7JV4KY',
  );
}
